config/routes.rb
Rails.application.routes.draw do
  
  root 'statics#main'
  devise_for :players
  
  resources :ships
  get 'ships/new/:id' => 'ships#new_ship_offer', as: :new_ship_offer
  get 'ships/:id/:section/report' => 'ships#section_report', as: :section_report
  
  resources :workers
  post 'courses' => 'courses#create'
  get 'courses/price' => 'courses#price'
  
  delete 'parts/:klass/:id' => 'parts#destroy', as: :sell_part
  patch 'parts/:klass/:id' => 'parts#update', as: :uninstall_part
  post 'parts/:klass/:id/discharge' => 'parts#discharge', as: :part_discharge
  
  get 'inspections' => 'inspections#index', as: :inspections
  get 'inspection/clusters' => 'inspections#clusters', as: :clusters_inspection
  get 'inspection/clusters/:id' => 'inspections#cluster', as: :cluster_inspection
  
  get 'inspection/ships' => 'inspections#ships', as: :ships_inspection
  get 'inspection/ships/:id' => 'inspections#ship', as: :ship_inspection

  get 'inspection/parts' => 'inspections#parts', as: :parts_inspection
  get 'inspection/parts/:klass/:id' => 'inspections#part', as: :part_inspection

  get 'inspection/workers' => 'inspections#workers', as: :workers_inspection
  get 'inspection/workers/:id' => 'inspections#worker', as: :worker_inspection
  
  
  

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/ship.rb
class Ship < ActiveRecord::Base
  
  include Kindsable #instances have kinds (1_1, ..., 5_2, ..., 10_3)
  
  attr_readonly [:kind, :stat_id]
  
  before_create :assign_stats, :set_tier_and_variant
  after_create :clusterize
  has_many :clusters, dependent: :destroy
  has_many :engines, dependent: :destroy
  has_many :workers, dependent: :destroy
  belongs_to :stat, class_name: 'ShipStat', foreign_key: 'stat_id'
  belongs_to :owner, class_name: 'Player', foreign_key: 'owner_id'
  
  validates :name,
    presence: true,
    length: { in: 5..45 },
    uniqueness: true
  validates :kind,
    presence: true
  validate :proper_kind?
  
  scope :by_tiers, ->(tiers) { where(tier: tiers) if tiers }
  scope :by_variants, ->(variants) { where(variant: variants) if variants }
  
  def propulsion_clusters
    Cluster.for_ship_section(self.id, 'propulsion')
  end
  
  def storage_clusters
    Cluster.for_ship_section(self.id, 'storage')
  end
  
  def armor_clusters
    Cluster.for_ship_section(self.id, 'armor')
  end
  
  def arsenal_clusters
    Cluster.for_ship_section(self.id, 'arsenal')
  end
  
  def command_clusters
    Cluster.for_ship_section(self.id, 'command')
  end
  
  def install_parts(parts, clusters=nil)
    installation = PartsInstallation.new(self)
    installation.create(parts: parts, clusters: clusters)
    
    # after installing parts it updates ship attributes
    #set_attr_values
  end
  
  def uninstall_parts(parts=nil, clusters=nil)
    installation = PartsInstallation.new(self)
    installation.destroy(parts: parts, clusters: clusters)
    
    
    # after installing parts it updates ship attributes
    #set_attr_values
  end
  
  def to_a
    [self]
  end
  
  def klass
    self.class.to_s.downcase
  end
  
  def big_klass
    self.class.to_s
  end
  
  def buy_by(owner)
    self.update_attribute(:owner_id, owner.id)
  end
  
  def sell
    self.destroy
  end
  
  def self.random_name
    Faker::Lorem.words(2).join(" ").capitalize
  end
  
  def parts
    parts_collection = []
    # final implementation not yet working
    
    # Cluster.SECTION_ASSIGNMENT.each_key do |part_type|
    #   parts_collection << self.send(part_type.pluralize).to_a
    # end
    
    # temporary implementation change when more part models will be added
    parts_collection << self.engines.to_a
    
    return parts_collection
  end
  
  private
  
    def assign_stats
      # assign ship to proper ShipStats
      self.stat_id = ShipStat.find_by(kind: self.kind).id
    end
    
    def set_tier_and_variant
      tier_and_variant = self.kind.split('_')
      self.tier = tier_and_variant.first
      self.variant = tier_and_variant.second
    end
    
    def clusterize
      # currently naive implementation
      stat.propulsion_clusters.times do |n|
        Cluster.create(
          section: 'propulsion',
          section_num: n+1,
          ship_id: self.id,
          stats: ({engine_slots: stat.engine_slots}).to_s)
      end
      
      stat.storage_clusters.times do |n|
        Cluster.create(
          section: 'storage',
          section_num: n+1,
          ship_id: self.id,
          stats: ({bay_slots: stat.bay_slots}).to_s)
      end
      
      stat.command_clusters.times do |n|
        Cluster.create(
          section: 'command',
          section_num: n+1,
          ship_id: self.id,
          stats: ({bridge_slots: stat.bridge_slots}).to_s)
      end
      
      stat.armor_clusters.times do |n|
        Cluster.create(
          section: 'armor',
          section_num: n+1,
          ship_id: self.id,
          stats: ({
            plating_slots: stat.plating_slots,
            barrier_slots: stat.barrier_slots,
            firewall_slots: stat.firewall_slots
            }).to_s
            )
      end
      
      stat.arsenal_clusters.times do |n|
        Cluster.create(
          section: 'arsenal',
          section_num: n+1,
          ship_id: self.id,
          stats: ({
            kineticgun_slots: stat.kineticgun_slots,
            emp_slots: stat.emp_slots,
            hack_slots: stat.hack_slots
            }).to_s
            )
      end
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  
  before_action :permit_signed_player
  before_action :get_player_ship, only: [:section_report]
  
  def index
    
  end

  def show
    # action avalible for other players
  end
  
  def section_report
    respond_to do |format|
      format.js {
        if Cluster::PART_ASSIGNMENT[params[:section].to_sym].nil?
            flash[:alert] = I18n.t('flash.error.ship.section')
            render :js => "window.location.href = '#{ship_path(@ship,format: 'html')}'"
        else
          
        end
      }
    end
  end

  def new
    @variant = params[:variant]
    if @variant.nil?
      @ship_stats = ShipStat.all[0...-1]
    else
      @ship_stats = ShipStat.where(variant: @variant)
    end
  end
  
  def new_ship_offer
    @ship_stat = ShipStat.find_by(id: params[:id])
    respond_to :js
  end
  
  def create
    if (@ship = Ship.new(
      kind: params[:kind],
      name: Ship.random_name,
      )) && @current_player.can_afford_ship?(params[:kind])
    
      @ship.save
      @current_player.buy(@ship)
      redirect_to @ship, flash: {notice: I18n.t('flash.successful.ship.creation')} and return
      
    else
      redirect_to new_ship_path, flash: {alert: I18n.t('flash.error.ship.creation')} and return
    end
  end

  def edit
    
  end
  
  def update
    
  end

  def delete
    
  end
  
  private
    
    def permit_signed_player
      if !player_signed_in?
        redirect_to new_player_session_path, flash: {alert: I18n.t('flash.error.player.not_logged_in')} and return
      end
    end
  
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_ship_offer.html.haml
.row#item-div
  .col-md-6
    %img{"data-src" => "holder.js/200x200/dark/text:Ship #{@ship_stat.kind} image"}
    = image_tag('ship.png', alt: "Ship #{@ship_stat.kind} image", size: '200')
    .price
      = t('activerecord.attributes.ship.price')
      = @ship_stat.price
      
    - if @ship_stat.price > @current_player.cash
      %div#too_expensive=t('links.item.too_expensive')
    - else
      .btn-own-outline
        = link_to t('links.ship.buy'), ships_path(kind: @ship_stat.kind), class: "btn btn-own btn-block", method: :post
  .col-md-6
    = render partial: 'ships/stat_chart'

app/views/ships/_stat_chart.html.haml
.chart
  .title
    = @ship_stat.name
  .stats
    .stat
      = t('activerecord.attributes.ship.propulsion_cluster.many')
      = @ship_stat.propulsion_clusters
      .indent-one
        = t('activerecord.attributes.ship.engine_slots')
        = @ship_stat.engine_slots
    .stat
      = t('activerecord.attributes.ship.arsenal_cluster.many')
      = @ship_stat.arsenal_clusters
      .indent-one
        = t('activerecord.attributes.ship.kineticgun_slots')
        = @ship_stat.kineticgun_slots
      .indent-one
        = t('activerecord.attributes.ship.emp_slots')
        = @ship_stat.emp_slots
      .indent-one
        = t('activerecord.attributes.ship.cos_slots')
        = @ship_stat.hack_slots
    .stat
      = t('activerecord.attributes.ship.armor_cluster.many')
      = @ship_stat.armor_clusters
      .indent-one
        = t('activerecord.attributes.ship.plating_slots')
        = @ship_stat.plating_slots
      .indent-one
        = t('activerecord.attributes.ship.barrier_slots')
        = @ship_stat.barrier_slots
      .indent-one
        = t('activerecord.attributes.ship.firewall_slots')
        = @ship_stat.firewall_slots
    .stat
      = t('activerecord.attributes.ship.storage_cluster.many')
      = @ship_stat.storage_clusters
      .indent-one
        = t('activerecord.attributes.ship.bay_slots')
        = @ship_stat.bay_slots
    .stat
      = t('activerecord.attributes.ship.command_cluster.one')
      = @ship_stat.command_clusters
      .indent-one
        = t('activerecord.attributes.ship.bridge_slots')
        = @ship_stat.bridge_slots

app/views/ships/delete.html.haml
%h1 Ships#delete
%p Find me in app/views/ships/delete.html.haml

app/views/ships/edit.html.haml
%h1 Ships#edit
%p Find me in app/views/ships/edit.html.haml

app/views/ships/index.html.haml
%h1 Ships#index
%p Find me in app/views/ships/index.html.haml

app/views/ships/new.html.haml
%div.shop-banner
  %img{"data-src" => "holder.js/100%x75/dark/text:Ship dealer banner"}
  
%ul#dark-tab.nav.nav-tabs
  %li{:class => @variant == nil ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.variants.all"), new_ship_path
  - 3.times do |n|
    %li{:class => @variant.to_i == n+1 ? 'active' : '', :role => "presentation"}
      = link_to t("links.ship.variants.t#{n+1}"), new_ship_path(variant: (n+1))
    
.row
  .col-md-3#item-link-divs
    = div_for(@ship_stats, class: "item-links") do |ship_stat|
      = link_to ship_stat.name, new_ship_offer_path(ship_stat), remote: true
  .col-md-9#item-divs

app/views/ships/new_ship_offer.js.erb
$('#item-div').detach().remove();
$("#item-divs").append("<%= escape_javascript(render partial: "ships/ship_offer") %>");

app/views/ships/show.html.haml
%div.show-banner
  

%ul#dark-tab.nav.nav-tabs
  %li{:class => @order == 'ship' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.show"), @ship
  %li{:class => @order == 'clusters' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_clusters"), ship_path(@ship, order: 'clusters')
  %li{:class => @order == 'parts' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_parts"), ship_path(@ship, order: 'parts')
  %li{:class => @order == 'workers' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_workers"), ship_path(@ship, order: 'workers')