config/routes.rb
Rails.application.routes.draw do
  
  root 'statics#main'
  devise_for :players
  
  resources :ships
  get 'ships/new/:id' => 'ships#new_ship_offer', as: :new_ship_offer
  get 'ships/:id/:section/report' => 'ships#section_report', as: :section_report
  
  resources :workers
  post 'courses' => 'courses#create'
  get 'courses/price' => 'courses#price'
  
  delete 'parts/:klass/:id' => 'parts#destroy', as: :sell_part
  patch 'parts/:klass/:id' => 'parts#update', as: :uninstall_part
  post 'parts/:klass/:id/discharge' => 'parts#discharge', as: :part_discharge
  
  get 'inspections' => 'inspections#index', as: :inspections
  get 'inspection/clusters' => 'inspections#clusters', as: :clusters_inspection
  get 'inspection/clusters/:id' => 'inspections#cluster', as: :cluster_inspection
  
  get 'inspection/ships' => 'inspections#ships', as: :ships_inspection
  get 'inspection/ships/:id' => 'inspections#ship', as: :ship_inspection

  get 'inspection/parts' => 'inspections#parts', as: :parts_inspection
  get 'inspection/parts/:klass/:id' => 'inspections#part', as: :part_inspection

  get 'inspection/workers' => 'inspections#workers', as: :workers_inspection
  get 'inspection/workers/:id' => 'inspections#worker', as: :worker_inspection
  
  
  

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/ship.rb
class Ship < ActiveRecord::Base
  
  include Kindsable #instances have kinds (1_1, ..., 5_2, ..., 10_3)
  
  attr_readonly [:kind, :stat_id]
  
  before_create :assign_stats, :set_tier_and_variant
  after_create :clusterize
  has_many :clusters, dependent: :destroy
  has_many :engines, dependent: :destroy
  has_many :workers, dependent: :destroy
  belongs_to :stat, class_name: 'ShipStat', foreign_key: 'stat_id'
  belongs_to :owner, class_name: 'Player', foreign_key: 'owner_id'
  
  validates :name,
    presence: true,
    length: { in: 5..45 },
    uniqueness: true
  validates :kind,
    presence: true
  validate :proper_kind?
  
  scope :by_tiers, ->(tiers) { where(tier: tiers) if tiers }
  scope :by_variants, ->(variants) { where(variant: variants) if variants }
  
  def propulsion_clusters
    Cluster.for_ship_section(self.id, 'propulsion')
  end
  
  def storage_clusters
    Cluster.for_ship_section(self.id, 'storage')
  end
  
  def armor_clusters
    Cluster.for_ship_section(self.id, 'armor')
  end
  
  def arsenal_clusters
    Cluster.for_ship_section(self.id, 'arsenal')
  end
  
  def command_clusters
    Cluster.for_ship_section(self.id, 'command')
  end
  
  def install_parts(parts, clusters=nil)
    installation = PartsInstallation.new(self)
    installation.create(parts: parts, clusters: clusters)
    
    # after installing parts it updates ship attributes
    #set_attr_values
  end
  
  def uninstall_parts(parts=nil, clusters=nil)
    installation = PartsInstallation.new(self)
    installation.destroy(parts: parts, clusters: clusters)
    
    
    # after installing parts it updates ship attributes
    #set_attr_values
  end
  
  def to_a
    [self]
  end
  
  def klass
    self.class.to_s.downcase
  end
  
  def big_klass
    self.class.to_s
  end
  
  def buy_by(owner)
    self.update_attribute(:owner_id, owner.id)
  end
  
  def sell
    self.destroy
  end
  
  def self.random_name
    Faker::Lorem.words(2).join(" ").capitalize
  end
  
  def parts
    parts_collection = []
    # final implementation not yet working
    
    # Cluster.SECTION_ASSIGNMENT.each_key do |part_type|
    #   parts_collection << self.send(part_type.pluralize).to_a
    # end
    
    # temporary implementation change when more part models will be added
    parts_collection << self.engines.to_a
    
    return parts_collection
  end
  
  private
  
    def assign_stats
      # assign ship to proper ShipStats
      self.stat_id = ShipStat.find_by(kind: self.kind).id
    end
    
    def set_tier_and_variant
      tier_and_variant = self.kind.split('_')
      self.tier = tier_and_variant.first
      self.variant = tier_and_variant.second
    end
    
    def clusterize
      # currently naive implementation
      stat.propulsion_clusters.times do |n|
        Cluster.create(
          section: 'propulsion',
          section_num: n+1,
          ship_id: self.id,
          stats: ({engine_slots: stat.engine_slots}).to_s)
      end
      
      stat.storage_clusters.times do |n|
        Cluster.create(
          section: 'storage',
          section_num: n+1,
          ship_id: self.id,
          stats: ({bay_slots: stat.bay_slots}).to_s)
      end
      
      stat.command_clusters.times do |n|
        Cluster.create(
          section: 'command',
          section_num: n+1,
          ship_id: self.id,
          stats: ({bridge_slots: stat.bridge_slots}).to_s)
      end
      
      stat.armor_clusters.times do |n|
        Cluster.create(
          section: 'armor',
          section_num: n+1,
          ship_id: self.id,
          stats: ({
            plating_slots: stat.plating_slots,
            barrier_slots: stat.barrier_slots,
            firewall_slots: stat.firewall_slots
            }).to_s
            )
      end
      
      stat.arsenal_clusters.times do |n|
        Cluster.create(
          section: 'arsenal',
          section_num: n+1,
          ship_id: self.id,
          stats: ({
            kineticgun_slots: stat.kineticgun_slots,
            emp_slots: stat.emp_slots,
            hack_slots: stat.hack_slots
            }).to_s
            )
      end
    end
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  
  def index 
    @text = I18n.t('elements.inspection.index')
  end
  
  def ships
    @text = I18n.t('elements.inspection.ships')
    @ships = @current_player.ships
    if params[:s_with_tier] && params[:s_tiers]
      s_tiers = params[:s_tiers].values.map(&:to_i)
      @ships = @ships.by_tiers(s_tiers)
    end
    if params[:s_of_variant] && params[:s_variants]
      s_variants = params[:s_variants].values.map(&:to_i)
      @ships = @ships.by_variants(s_variants)
    end
    respond_to do |format|
      format.html {
        if @ships.empty?
          redirect_to inspections_path, flash: {alert: I18n.t('flash.error.ship.ships_not_found')}
        end
      }
      format.json { render json: {ships_found: @ships.count} }
    end
  end
  
  def ship
    get_player_ship
    @ship_stat = @ship.stat
  end
  
  def clusters
    get_player_ship(id: params[:c_ship_id])
    if params[:c_specific_section] && safe_section?(params[:c_section])
      cluster_expr = "#{params[:c_section]}_clusters"
      @clusters = @ship.send(cluster_expr)
    else
      @clusters = @ship.clusters
    end
  end
  
  def cluster
    get_player_ship(id: params[:c_ship_id])
    @cluster = @ship.clusters.find_by(id: params[:id])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def parts
    if params[:p_selection] == 'all'
      part_params = {}
      @text = I18n.t('elements.inspection.parts.all')
    elsif params[:p_selection] == 'free'
      part_params = {ship_id: nil}
      @text = I18n.t('elements.inspection.parts.not_installed')
    elsif params[:p_selection] == 'shipped'
      get_player_ship(id: params[:p_ship_id])
      part_params = {ship_id: params[:p_ship_id]}
      @text = I18n.t('elements.inspection.parts.installed', name: @ship.name)
    end
    
    if params[:p_specific_klass] == 'true' && safe_klass?(params[:p_klass])
      part_expr = params[:p_klass].downcase.pluralize # returns engines for Engine
      @parts = @current_player.send(part_expr).where(part_params)
    else
      @parts = @current_player.parts(part_params)
    end
  rescue NoMethodError
    @parts = [[]]
  ensure
    respond_to do |format|
      format.html
      format.json { render json: {parts_found: @parts.flatten.count}}
    end
  end
  
  def part
    get_player_part
    @hp_index = @part.hp_index
    respond_to do |format|
      format.html
      format.js
    end
  end

  def workers
    @workers = @current_player.workers
    @text = I18n.t('elements.worker.all_employed')
    if params[:w_selection] == 'free'
      @workers = @workers.free
      @text = I18n.t('elements.worker.not_assigned')
    elsif params[:w_selection] == 'not_shipped'
      @workers = @workers.not_shipped
      @text = I18n.t('elements.worker.not_shipped')
    elsif params[:w_selection] == 'shipped' && get_player_ship(id: params[:w_ship_id])
      @workers = @ship.workers
      @text = I18n.t('elements.worker.shipped', name: @ship.name)
    end
    respond_to do |format|
      format.html
      format.json {render json: {workers_found: @workers.count}}
    end
  end
  
  def worker
    get_player_worker
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  private
    
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_cluster.html.haml
%div#item-div
  .row
    .col-md-12
      .item-name
        %span
          = @cluster.name
  .row
    .col-md-7
      .item-stat
        .item-stat-header= t('elements.cluster.free_slots')
        - @cluster.stat.each do |key, val|
          - part_klass = key.to_s.split('_').first
          %div= t("elements.cluster.#{part_klass}", slots: @cluster.free_slots_for(part_klass))
      
      
      - if (parts = @cluster.parts).empty?
        .alert.alert-danger= t('elements.cluster.no_parts')
      - else
        .item-stat
          .item-stat-header= t('elements.cluster.parts')
          - parts.each do |part|
            %div= link_to part.name, part_inspection_path(id: part, klass: part.big_klass), remote: true
      
      - if (workers = @cluster.workers).empty?
        .alert.alert-danger= t('elements.cluster.no_workers')
      - else
        .item-stat
          .item-stat-header= t('elements.cluster.workers')
          - workers.each do |worker|
            %div= link_to worker.name, worker_inspection_path(worker), remote: true
        
    .col-md-5
      .chart
        .title= t('elements.item.stats')
        
        = t('elements.cluster.slots')
        .stats
          - @cluster.stat.each do |key, val|
            %div.indent-one= t("elements.cluster.#{key.to_s.split('_').first}", slots: val)
        
        .title= t('elements.item.manage')

app/views/inspections/_navigation.html.haml
%ul#dark-tab.nav.nav-tabs
  %li{:class => params[:action] == 'ship' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.show"), ship_inspection_path(@ship)
  %li{:class => params[:action] == 'clusters' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_clusters"), clusters_inspection_path(c_ship_id: @ship.id)
  %li{:class => params[:action] == 'parts' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_parts"), parts_inspection_path(p_selection: 'shipped', p_ship_id: @ship.id)
  %li{:class => params[:action] == 'workers' ? 'active' : '', :role => "presentation"}
    = link_to t("links.ship.by_workers"), workers_inspection_path(w_selection: 'shipped', w_ship_id: @ship.id)

app/views/inspections/_part.html.haml
%div#item-div
  .row
    .col-md-12
      .item-name
        %span
          = @part.name
          = t("activerecord.attributes.part.kind", kind: @part.kind)
      .progress-bar-label= "HP #{@part.hp}/#{@part.stat.hp_base} (#{@hp_index}%)"
      .progress#progress-hp
        .progress-bar.progress-bar-danger{"aria-valuemax" => "100",
          "aria-valuemin" => "0", "aria-valuenow" => @hp_index,
          :role => "progressbar", :style => "width: #{@hp_index}%"}
        %span.progress-bar-label
  .row
    .col-md-6
      .item-stat
        .item-stat-header= t('activerecord.attributes.part.effective_stats')
        - Partable::ATTRIBUTES[@part.klass.to_sym].each do |attrib|
          %div
            = t("activerecord.attributes.#{@part.klass}.#{attrib}")
            = @part.send(attrib)

      - if @part.workers.empty?
        .alert.alert-danger= t('elements.part.no_workers')
      - else
        .item-stat
          .item-stat-header= t('elements.part.workers')
          - @part.workers.each do |worker|
            %div= link_to worker.name, 
              worker_inspection_path(worker),
              remote: true
      
      - if @part.ship.nil?
        .alert.alert-info= t('elements.part.not_installed')
      - else
        .item-stat
          .item-stat-header= t('elements.part.installed_in')
          %div
            = t("elements.part.installation.cluster")
            = link_to @part.cluster.name,
              cluster_inspection_path(@part.cluster, c_ship_id: @part.ship_id),
              remote: true
          %div
            = t("elements.part.installation.ship")
            = link_to @part.ship.name, ship_inspection_path(@part.ship)
    .col-md-6
      .chart
        .title= t('elements.item.stats')
        - @part.stat.stat.each do |k, v|
          %div= t("activerecord.attributes.part.#{k}", val: v)
      .chart
        .title= t('elements.item.manage')
        .btn-own-outline
          = link_to t('links.part.sell'),
            sell_part_path(id: @part.id, klass: @part.big_klass),
            method: :delete, class: "btn btn-own btn-block"
        .btn-own-outline
          = link_to t('links.part.uninstall'),
            uninstall_part_path(id: @part.id, klass: @part.big_klass),
            method: :patch,
            class: "btn btn-own btn-block"
        .btn-own-outline
          = link_to t('links.part.discharge.workers'), '#',
            class: "btn btn-own btn-block", id: "btn-discharge-form"
            
        .item-stat#discharge-form
          = form_tag part_discharge_path(klass: @part.big_klass, id: @part.id), method: :post, remote: true do |f|
            // = hidden_field_tag(:klass, @part.big_klass)
            // = hidden_field_tag(:id, @part.id)
            .input-group
              = check_box_tag(:all, true, false)
              = label_tag(:all, t("links.part.discharge.de_select_all"))
            - @part.workers.each do |worker|
              .input-group
                = check_box_tag("worker_ids[#{worker.id}]", worker.id, false, class: 'worker-id-check')
                = label_tag("worker_ids[#{worker.id}]", worker.name)
            .btn-own-outline#submit
              = submit_tag(t('links.part.discharge.submit'),
              class: 'btn btn-own btn-block',
              data: { confirm: t('links.course.accept') })

app/views/inspections/_worker.html.haml
%div#item-div
  .row
    .col-md-12
      .item-name
        %span= @worker.name
  .row
    .col-md-6
      .item-stat
        .item-stat-header= t("activerecord.attributes.worker.skills")
        - @worker.skills.each do |skill_and_value|
          %div= t("activerecord.attributes.worker.#{skill_and_value[0]}", val: skill_and_value[1])
      
      
      - if @worker.crewable.nil?
        .alert.alert-info= t('elements.worker.not_delegated')
      - else
        .item-stat
          .item-stat-header= t('activerecord.attributes.worker.delegated_to')
          %div
            = t("activerecord.attributes.worker.delegation.part")
            = link_to @worker.crewable.name, part_inspection_path(id: @worker.crewable, klass: @worker.crewable.big_klass), remote: true
          - if @worker.ship
            %div
              = t("activerecord.attributes.worker.delegation.cluster")
              = link_to @worker.crewable.cluster.name, cluster_inspection_path(@worker.crewable.cluster, c_ship_id: @worker.ship_id), remote: true
            %div
              = t("activerecord.attributes.worker.delegation.ship")
              = link_to @worker.ship.name, @worker.ship #, show_ship_item_path(@worker.ship), remote: true
          - else
            .alert.alert-info= t('elements.worker.not_shipped')
    .col-md-6
      .chart
        .title= t('elements.item.manage')
        .btn-own-outline
          = link_to t('links.worker.fire'), @worker, method: :delete,
            class: "btn btn-own btn-block"
        .btn-own-outline
          = link_to t('links.worker.discharge'), worker_path(@worker), method: :patch,
            class: "btn btn-own btn-block"
        .btn-own-outline
          = link_to t('links.course.train'), '#',
            class: "btn btn-own btn-block", id: "btn-training-form"
        .item-stat#training-form
          .item-stat-header= t('elements.course.name')
          = form_tag courses_path, method: :post, remote: true do
            = hidden_field_tag(:worker_id, @worker.id)
            .input-group
              = label_tag(:topic, t("links.course.topic"))
              - translated_topics = Worker::TOPICS.map{|topic| [t("activerecord.attributes.#{topic}.name"), topic] }
              = select_tag(:topic, options_for_select(translated_topics), include_blank: true, class: 'form-control input-sm form-element')
            %div#hide-lvl1
              .input-group#train_by{ :'data-translation' => t('links.course.by') }
                = radio_button_tag(:relative, "true", true, class: 'form-element')
                = label_tag(:relative_true, t("links.course.train_by"))
              .input-group#train_to{ :'data-translation' => t('links.course.to') }
                = radio_button_tag(:relative, "false", false, class: 'form-element')
                = label_tag(:relative_false, t("links.course.train_to"))
              .input-group
                = label_tag(:course_points, t("links.course.by"), id: 'points-label')
                = number_field_tag(:course_points, nil, in: 1..100, step: 1, class: 'form-element')
                = label_tag(:course_points, t("links.course.pts"), id: 'points-label2')
              .input-group#course-price{ :'data-path' => courses_price_path }
                = label_tag(:price, t("elements.course.price"))
                %span
              .alert.alert-danger#course-price-alert= t('elements.player.no_cash_for_course')
              %div#hide-lvl2
                .btn-own-outline
                  = submit_tag(t('links.course.submit'), class: 'btn btn-own btn-block', data: { confirm: t('links.course.accept') })
        
= javascript_include_tag 'page_specific/worker_course_form'

app/views/inspections/cluster.js.erb
$("#item-div").detach().remove();
$("#item-divs").prepend("<%= escape_javascript(render partial: 'inspections/cluster')%>")
$('#flash-container').detach().remove();
$('#flash-container-out').prepend("<%= escape_javascript(render partial: 'layouts/flash_container')%>");
$('#player-founds').children('#cash').text("<%= @current_player.cash %>")

app/views/inspections/clusters.html.haml
%div#inspection-banner
  %span= t('elements.inspection.clusters', name: @ship.name)
.row
  .col-md-9
    = t('texts.inspection.clusters')
  .col-md-3
    .btn-own-outline
      = link_to t('links.inspection.to_index'), inspections_path, class: 'btn btn-own btn-block'
= render partial: 'inspections/navigation'
.row
  .col-md-4#item-link-divs
    = div_for(@clusters, class: "item-links") do |cluster|
      = link_to cluster.name, cluster_inspection_path(cluster, c_ship_id: @ship.id), remote: true
  .col-md-8#item-divs
    = render partial: 'inspections/cluster' if @cluster

app/views/inspections/index.html.haml
%div#inspection-banner
  %span= @text
%p= t('texts.inspection.index')
.row
  .col-md-4
    .item-stat.inspect-form
      .item-stat-header
        = t('elements.ship.ships')
        
      .btn-own-outline
        = link_to t('links.ship.inspect.all'), ships_inspection_path, class: 'btn btn-own btn-block'
      %hr
      - if @current_player.ships.count < 4
        = div_for @current_player.ships do |ship|
          = link_to ship.name, ship_inspection_path(ship)
        %hr
        
      = form_tag ships_inspection_path, method: :get do
        .input-group
          = check_box_tag :s_with_tier, true, false, class: 'form-element s-form-element'
          = label_tag :s_with_tier, t('links.ship.inspect.with_tier')
        .row#s-tiers-checkboxes
          .col-md-5.col-md-offset-1
            - (1..5).each do |n|
              .input-group
                = check_box_tag "s_tiers[#{n}]", n, false, class: 's-tier-check s-form-element'
                = label_tag "s_tiers[#{n}]", t('activerecord.attributes.tier', tier: n)
          .col-md-6
            - (6..10).each do |n|
              .input-group
                = check_box_tag "s_tiers[#{n}]", n, false, class: 's-tier-check s-form-element'
                = label_tag "s_tiers[#{n}]", t('activerecord.attributes.tier', tier: n)
        
        .input-group
          = check_box_tag :s_of_variant, true, false, class: 'form-element s-form-element'
          = label_tag :s_of_variant, t('links.ship.inspect.of_variant')
        .row#s-variants-checkboxes
          .col-md-11.col-md-offset-1
            - (1..3).each do |n|
              .input-group
                = check_box_tag "s_variants[#{n}]", n, false, class: 's-variant-check s-form-element'
                = label_tag "s_variants[#{n}]", t("activerecord.attributes.ship.variants.t#{n}.one")
        .response#s_found{:'data-path' => ships_inspection_path}
          = t('links.inspection.found')
          %span
        .btn-own-outline.submit#s-submit
          = submit_tag t('links.inspection.show'), class: 'btn btn-own btn-block'
          
  .col-md-4
    .item-stat.inspect-form
      .item-stat-header
        = t('elements.part.parts')
      // .btn-own-outline
      //   = link_to t('links.part.inspect.all'), parts_inspection_path, class: 'btn btn-own btn-block'
      %hr
      = form_tag parts_inspection_path, method: :get do
        #p-selections
          .input-group
            = radio_button_tag :p_selection, 'all', false, class: 'form-element  p-form-element'
            = label_tag :p_selection_all, t('links.part.inspect.all')
          .input-group
            = radio_button_tag :p_selection, 'free', false, class: 'form-element  p-form-element'
            = label_tag :p_selection_free, t('links.part.inspect.not_installed')
          .input-group
            = radio_button_tag :p_selection, 'shipped', false, class: 'form-element  p-form-element'
            = label_tag :p_selection_shipped, t('links.part.inspect.installed_on')
        .input-group
          = select_tag :p_ship_id,
            options_from_collection_for_select(@current_player.ships, :id, :name),
            class: 'form-control input-sm form-element p-form-element'
        .input-group
          = check_box_tag :p_specific_klass, 'true', false, class: 'form-element  p-form-element'
          = label_tag :p_specific_klass, t('links.part.inspect.specific_klass')
        .input-group
          - translated_klass = Partable::KLASSES.map{|klass| [t("elements.part.klass.#{klass.downcase}.few"), klass]}
          = select_tag :p_klass,
            options_for_select(translated_klass),
            class: 'form-control input-sm form-element p-form-element'
        .response#p_found{:'data-path' => parts_inspection_path}
          = t('links.inspection.found')
          %span
        .btn-own-outline.submit#p-submit
          = submit_tag(t('links.inspection.show'), class: 'btn btn-own btn-block')
          
  .col-md-4
    .item-stat.inspect-form
      .item-stat-header
        = t('elements.worker.workers')
      .btn-own-outline
        = link_to t('links.worker.inspect.all'), workers_inspection_path, class: 'btn btn-own btn-block'
      %hr
      = form_tag workers_inspection_path, method: :get do
        #w-selections
          .input-group
            = radio_button_tag :w_selection, 'free', false, class: 'form-element w-form-element'
            = label_tag :w_selection_free, t('links.worker.inspect.not_assigned')
          .input-group
            = radio_button_tag :w_selection, 'not_shipped', false, class: 'form-element w-form-element'
            = label_tag :w_selection_not_shipped, t('links.worker.inspect.not_shipped')
          .input-group
            = radio_button_tag :w_selection, 'shipped', false, class: 'form-element w-form-element'
            = label_tag :w_selection_shipped, t('links.worker.inspect.shipped')
        .input-group
          = select_tag :w_ship_id,
            options_from_collection_for_select(@current_player.ships, :id, :name),
            class: 'form-control input-sm form-element w-form-element'
        .response#w_found{:'data-path' => workers_inspection_path}
          = t('links.inspection.found')
          %span
        .btn-own-outline.submit#w-submit
          = submit_tag(t('links.inspection.show'), class: 'btn btn-own btn-block')
          
= javascript_include_tag 'page_specific/inspections_forms'
      

app/views/inspections/part.js.erb
$("#item-div").detach().remove();
$("#item-divs").prepend("<%= escape_javascript(render partial: 'inspections/part')%>")
$('#flash-container').detach().remove();
$('#flash-container-out').prepend("<%= escape_javascript(render partial: 'layouts/flash_container')%>");
$('#player-founds').children('#cash').text("<%= @current_player.cash %>")

app/views/inspections/parts.html.haml
%div#inspection-banner
  %span= @text
.row
  .col-md-9
    = t('texts.inspection.parts')
  .col-md-3
    .btn-own-outline
      = link_to t('links.inspection.to_index'), inspections_path, class: 'btn btn-own btn-block'
= render partial: 'inspections/navigation' if @ship
.row
  .col-md-4#item-link-divs
    - @parts.each do |part_type|
      = div_for(part_type, class: "item-links") do |part|
        = link_to part.name, part_inspection_path(id: part.id, klass: part.big_klass), remote: true
  .col-md-8#item-divs
    = render partial: 'inspections/part' if @part

app/views/inspections/ship.html.haml
%div#inspection-banner
  %span= t('elements.inspection.ship', name: @ship.name)
.row
  .col-md-9
    = t('texts.inspection.ship', name: @ship.name)
  .col-md-3
    .btn-own-outline
      = link_to t('links.inspection.to_index'), inspections_path, class: 'btn btn-own btn-block'

= render partial: 'inspections/navigation'

.item-name
  %span= t('elements.ship.ship') + @ship.name + " | " + @ship_stat.name
.row
  .col-md-4
    .item-stat
      .item-stat-header= t('elements.ship.stats')
      - Partable::KLASSES.each do |klass|
        - if !(klass_val = @ship.try(klass.downcase)).nil?
          %div= klass + " = " + klass_val.to_s
  .col-md-4
    = t('elements.ship.show_reports')
    - Cluster::PART_ASSIGNMENT.each_key do |section|
      %div{class: "#{section}"}
        = link_to t("links.ship.report.#{section.downcase}"), section_report_path(@ship, section.downcase), remote: true
        %div{class: "#{section}-report"}
  .col-md-4
    = t('elements.ship.chart')
    = render 'ships/stat_chart'

app/views/inspections/ships.html.haml
%div#inspection-banner
  %span= @text
.row
  .col-md-9
    = t('texts.inspection.ships')
  .col-md-3
    .btn-own-outline
      = link_to t('links.inspection.to_index'), inspections_path, class: 'btn btn-own btn-block'
      
- @ships.each do |ship|
  %div= link_to ship.name, ship_inspection_path(ship)

app/views/inspections/worker.js.erb
$("#item-div").detach().remove();
$("#item-divs").prepend("<%= escape_javascript(render partial: 'inspections/worker')%>")
$('#flash-container').detach().remove();
$('#flash-container-out').prepend("<%= escape_javascript(render partial: 'layouts/flash_container')%>");
$('#player-founds').children('#cash').text("<%= @current_player.cash %>")

app/views/inspections/workers.html.haml
%div#inspection-banner
  %span= @text
.row
  .col-md-9
    = t('texts.inspection.workers')
  .col-md-3
    .btn-own-outline
      = link_to t('links.inspection.to_index'), inspections_path, class: 'btn btn-own btn-block'
= render partial: 'inspections/navigation' if @ship
.row
  .col-md-4#item-link-divs
    = div_for(@workers, class: "item-links") do |worker|
      = link_to worker.name, worker_inspection_path(worker), remote: true
  .col-md-8#item-divs
    = render partial: 'inspections/worker' if @worker