config/routes.rb
Rails.application.routes.draw do
  
  root 'statics#main'
  devise_for :players
  
  resources :ships
  get 'ships/new/:id' => 'ships#new_ship_offer', as: :new_ship_offer
  get 'ships/:id/:section/report' => 'ships#section_report', as: :section_report
  
  resources :workers
  post 'courses' => 'courses#create'
  get 'courses/price' => 'courses#price'
  
  delete 'parts/:klass/:id' => 'parts#destroy', as: :sell_part
  patch 'parts/:klass/:id' => 'parts#update', as: :uninstall_part
  post 'parts/:klass/:id/discharge' => 'parts#discharge', as: :part_discharge
  
  get 'inspections' => 'inspections#index', as: :inspections
  get 'inspection/clusters' => 'inspections#clusters', as: :clusters_inspection
  get 'inspection/clusters/:id' => 'inspections#cluster', as: :cluster_inspection
  
  get 'inspection/ships' => 'inspections#ships', as: :ships_inspection
  get 'inspection/ships/:id' => 'inspections#ship', as: :ship_inspection

  get 'inspection/parts' => 'inspections#parts', as: :parts_inspection
  get 'inspection/parts/:klass/:id' => 'inspections#part', as: :part_inspection

  get 'inspection/workers' => 'inspections#workers', as: :workers_inspection
  get 'inspection/workers/:id' => 'inspections#worker', as: :worker_inspection
  
  
  

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/views/layouts/_flash_container.html.haml
%div#flash-container
  - if flash[:notice]
    %p.alert.alert-info.alert-dismissable
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      = flash[:notice]
  - if flash[:alert]
    %p.alert.alert-danger.alert-dismissable
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      = flash[:alert]

app/views/layouts/_footer.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom.navbar-inverse
  .container-fluid
    %ul.nav.navbar-nav
      %li
        %a{:href => "#"}
          Link
      %li
        %a{:href => "#"} Link
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Dropdown
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"} Action
          %li
            %a{:href => "#"} Another action
          %li
            %a{:href => "#"} Something else here
          %li.divider
          %li
            %a{:href => "#"} Separated link
          %li.divider
          %li
            %a{:href => "#"} One more separated link
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{:href => "#"} Link
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Przydatne
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            = link_to 'routes', rails_routes_path if Rails.env != 'production'
          %li
            = link_to 'ship dealer', new_ship_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Brand', root_path, class: 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"}
            Link
            %span.sr-only (current)
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
            %li.divider
            %li
              %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        - if player_signed_in?
          %li
            %a{:href => "#"} Link
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = @current_player.name
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li= link_to t('links.player.logout'), destroy_player_session_path, method: :delete
        - else
          
          %li= link_to t('links.player.register'), new_player_registration_path
          %li= link_to t('links.player.login'), new_player_session_path

app/views/layouts/_player_nav.html.haml
.player-name
  = @current_player.name
.player-image
  = image_tag('pilot_icon_sm.png', alt: 'player image', size: '100')
  
#player-founds
  Money:
  %span#cash= @current_player.cash
.btn.btn-dark.btn-block
  Btn text
%p
  Payer profile and navigation will be here someday.
  
%ol.manage
  = link_to t('elements.inspection.index'), inspections_path
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GameSpaceships
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    
    = render 'layouts/header'
    .container
      %div#flash-container-out= render 'layouts/flash_container'
      .row
        .col-md-3
          .my-container-outline
            .my-container
              - if player_signed_in?
                = render 'layouts/player_nav'
              - else
                = render text: 'Here will be login form and button to register'
        .col-md-9
          .my-container-outline
            .my-container#main-container
              = yield
    = render 'layouts/footer'